apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  selector:
    app: cicd-master
    environment: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort